### ISSUE TITLE
Time Format is not work???

### ISSUE THREAD

**Issue by my-dev** [sue445/fluent-plugin-out_chatwork#5]
Nice to meet you.
Mr, sue445...

Thank You your nice plugin...

by reading log file...
In this log file, [ 2015-06-12 00:00:00 ] is written...
But In ChatWork Message, it's changed to 1434034800...

my td-agent.conf is below...

\---------------------------------------------------------------------
\<match zzz>
type chatwork
api_token xxxxx
room_id yyyyy
message '[info][title][warning][\<%= tag %>]@\<%= record["xxx"] %>[/title]時刻：\<%= time %>\n[/info]'
\</match>
\---------------------------------------------------------------------

And Please support [ JST Timezone ]...

If you can do, Please invastigate...
Thank you...

**Comment by sue445** [comment]
> But In ChatWork Message, it's changed to 1434034800...

I think that it is a specification of fluentd

http://docs.fluentd.org/articles/config-file#1-ldquosourcerdquo-where-all-the-data-come-from
-> **The time field is specified by input plugins, and it must be in the Unix time format**

If you want to print specified format, use [Time#at](http://ruby-doc.org/core-2.2.0/Time.html#method-c-at) and [Time#strftime](http://ruby-doc.org/core-2.2.0/Time.html#method-i-strftime) at ruby core class

example

```
message '[info][title][warning][<%= tag %>]@<%= record["xxx"] %>[/title]時刻：<%= Time.at(time).strftime("%Y/%m/%d %H:%M:%S") %>\n[/info]'
```

> Mrs, sue445...

I'm a man :man:

**Comment by my-dev** [comment]
Hi! Mr,sue445.

Thank you your response.
I try this way.

And sorry, You're a man. sorry.m(_ _);m

Thank You.

**Comment by my-dev** [comment]
this issue is resolved.

thank you.
